#EINSUM

There's a good chance that einsum will help us do this faster and more memory-efficiently than combinations of the NumPy functions like multiply, sum and transpose will allow.

good ans also: stackoverflow.com/questions/26089893/understanding-numpys-einsum

In [1]:
import numpy as np

In [2]:
#matrix values
A = np.random.rand(3,5)
B = np.random.rand(5,2)
M = np.empty((3, 2))
print(A)

[[0.49689075 0.56191633 0.10562608 0.84793775 0.29310636]
 [0.58965569 0.03805157 0.86491844 0.48495865 0.14606506]
 [0.46341741 0.14306762 0.62983255 0.09266492 0.62176348]]


In [3]:
#Matrix multiplication normal
for i in range(3):
    for j in range(2):
        total = 0
        for k in range(5):
            total += A[i, j]*B[k,j]

        M[i, j] = total
        print(M[i,j])

0.8343701880687902
0.7238498211181833
0.9901394361375058
0.04901729962776789
0.7781623362115598
0.18429695885467567


In [4]:
#einsum Multiplication
N = np.einsum('ik, kj->ij', A, B)   
# i,j :free indices(specified in the output) 
# K :summation index(input but not in the output)
print(N)

[[0.67127328 0.4224541 ]
 [0.8919592  0.52711808]
 [0.71773782 0.59793132]]


In [8]:
#Example 2
a = np.random.rand(5)
b = np.random.rand(3)
outer = np.einsum('i,j->ij', a, b)
#no summation index
print(outer)

[[0.01083832 0.35710684 0.02367074]
 [0.00432432 0.14248018 0.00944426]
 [0.0114896  0.37856558 0.02509312]
 [0.02278255 0.75065186 0.04975677]
 [0.00974663 0.32113745 0.02128651]]


In [9]:
for i in range(5):
    for j in range(3):
        total = 0
        #no sum loop 
        total+= a[i]*b[j]
        outer[i,j] = total
        print(outer[i,j])

0.010838317980301559
0.35710683677406274
0.02367073549110986
0.004324323650029015
0.14248018397834128
0.00944426261379531
0.011489598321554426
0.3785655781526278
0.025093122684064998
0.02278254774150259
0.7506518605939342
0.04975676690634292
0.009746634385681845
0.32113744780233067
0.021286513727622875


RULER FOR EINSUM:

1. Repeating letters in different inputs means those values will be multiplied
   and those products will be the output.

   M = np.einsum('ik, kj', A, B)

2. Omitting a letter means that axis will be summed.
   
   x = np.ones(3)
   sum_x = np.einsum('i->', x)

3. We can return the unsummed axes in any order.(reversed output (3,4,5)).

   x = np.ones((5, 4, 3))
   np.einsum('ijk->kji', x)

In [10]:
#pytorch
import torch

x = torch.rand((2, 3))

In [11]:
# Permutation of Tensors
torch.einsum("ij->ji", x)

tensor([[0.5908, 0.0256],
        [0.4295, 0.9669],
        [0.7050, 0.4145]])

In [12]:
# Summation
torch.einsum("ij->", x)

tensor(3.1322)

In [13]:
# Column Sum
torch.einsum("ij->j", x)

tensor([0.6164, 1.3963, 1.1195])

In [14]:
# Row sum
torch.einsum("ij->i", x)

tensor([1.7253, 1.4070])

In [15]:
# Matrix-Vector Multiplication
v = torch.rand((1,3))
torch.einsum("ij, kj->ik", x, v)  #no reshaping needed

tensor([[0.9600],
        [0.7298]])

In [16]:

# Matrix-Matrix Multiplication
torch.einsum("ij, kj->ik", x, x)  #2x2 : 2x3 X 3x2

tensor([[1.0305, 0.7226],
        [0.7226, 1.1073]])

In [17]:
# Dot product first row with first row of Matrix
torch.einsum("i,i ->", x[0], x[0])

tensor(1.0305)

In [18]:

# Dot product with Matrix
torch.einsum("ij, ij->", x, x)

tensor(2.1378)

In [19]:
# Hadamard Product (element wise Multiplication)
torch.einsum("ij,ij->ij", x, x)

tensor([[3.4907e-01, 1.8443e-01, 4.9700e-01],
        [6.5352e-04, 9.3482e-01, 1.7185e-01]])

In [20]:
# Outer product
a = torch.rand((3))
b = torch.rand((5))
torch.einsum("i, j->ij", a, b)

tensor([[0.3319, 0.1552, 0.0116, 0.2914, 0.1100],
        [0.4526, 0.2116, 0.0159, 0.3974, 0.1500],
        [0.0875, 0.0409, 0.0031, 0.0768, 0.0290]])

In [21]:
# Batch Matrix Multiplication
a = torch.rand((3, 2, 5))
b = torch.rand((3, 5, 3))
torch.einsum("ijk, ikl->ijl", a, b)

tensor([[[1.3452, 1.8237, 2.2880],
         [1.0043, 1.1377, 1.1133]],

        [[1.7027, 2.0008, 1.4459],
         [1.5870, 1.8057, 1.7491]],

        [[1.9639, 1.5182, 1.4187],
         [1.9054, 1.5489, 1.4941]]])

In [22]:
#Matrix Diagonal
x  = torch.rand((3,3))
torch.einsum("ii->i", x)

tensor([0.9214, 0.3435, 0.7485])

In [23]:
# Matrix Trace (Sum of the Diagonal)
torch.einsum("ii->", x)

tensor(2.0135)